In [2]:
import numpy as np

In [5]:
A=np.array([4,5,6])
B=[1,2,3]
np.copyto(A,B)
print(A)

[1 2 3]


In [6]:
A=np.array([[1,2,3],[4,5,6]])
B=[[4,5,6],[7,8,9]]
np.copyto(A,B)
A

array([[4, 5, 6],
       [7, 8, 9]])

In [8]:
import numpy as np
print(np.ndim([[1,2,3],[4,5,6]]))
print(np.ndim(np.array([[1,2,3],[4,5,6]])))
print(np.ndim(1))

2
2
0


In [20]:
print(np.shape(np.eye(3)))
print(np.shape([[1,3]]))
print(np.shape([0]))
print(np.shape(0))

(3, 3)
(1, 2)
(1,)
()


In [18]:
a=np.array([(1,2),(3,4),(5,6)],dtype=[('x','i4'),('y','i4')])
print(np.shape(a)[0])
a.shape

3


(3,)

In [26]:
a=np.array([[1,2,3],[4,5,6]])
print(np.size(a))
print(np.size(a,1))
print(np.size(a,0))

6
3
2


#reshape

In [28]:
a=np.arange(6).reshape((3,2))
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [31]:
print(np.reshape(a,(2,3)))
print(np.reshape(np.ravel(a),(2,3)))

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [34]:
a = np.array([[1,2,3], [4,5,6]])
print(np.reshape(a,(3,-1)))

[[1 2]
 [3 4]
 [5 6]]


In [35]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [48]:
x = np.zeros((3, 4))
print(x)
np.transpose(x).shape
np.moveaxis(x,1,1).shape

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


(3, 4)

In [3]:
x=np.array([[1,2],[3,4]])
print(np.flip(x,1))

[[2 1]
 [4 3]]


In [14]:
def time_scale_signal(x : np.ndarray, k : int) -> np.ndarray:
    # implement this function
    a=np.ones(len(x))
    np.copyto(a,x)
    p=len(x)
    for i  in range(p):
        if(i*k)>=p:
            x[i]=0
        else:
            x[i]=a[(i*k)]
        
    return x
x = np.array([0, 0, 0, 0, 0, 0.5, 2, 1, 0.5, 1, 0, 0, 0, 0, 0, 0, 0])
print(time_scale_signal(x,2))

[0.  0.  0.  2.  0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]


In [16]:
arr = np.array([0, 0, 0, 0, 0, 0.5, 2, 1, 0.5, 1, 0, 0, 0, 0, 0, 0, 0])
n = len(arr)
np.interp(np.linspace(0, n, 2*n+1), np.arange(n), arr)

array([0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 ,
       1.25, 2.  , 1.5 , 1.  , 0.75, 0.5 , 0.75, 1.  , 0.5 , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  ])

In [25]:
a=np.array([1,2,3,4,5,6,7,8])
b=np.roll(a,-2)
b[-2:]=0
b

array([3, 4, 5, 6, 7, 8, 0, 0])

In [29]:
x=np.arange(-8,9,1)
x

array([-8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])