In [5]:
import numpy as np

In [13]:
#Mutable
a=np.array([1,3,2,4,5])
b=[1,3,2,4,5]
b[2:5]
x=a[0:3] #x is VIEW of a
y=b[0:3]
print(x,y)
x[0]=6
y[0]=14
print(a)
print(b)
print(a[2:5])

[1 3 2] [1, 3, 2]
[6 3 2 4 5]
[1, 3, 2, 4, 5]
[2 4 5]


In [109]:
mat=np.array([[1,2],[3,4],[5,6]])
print(mat)
print(mat.ndim) #no of dimensions
print(mat.shape) #(rowa,cols)
print(mat.size) #how many items
print(mat.dtype)#datatypes

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
6
int64


In [19]:
a=100398938385838378937573739737837893783787478749827493749742742
b=7598347593798375937587587385739873478937489729472479827498274827497244274729847
print(a+b)

7598347593798376037986525771578252416511229467310373611285753577324738024472589


In [21]:
a=np.zeros(4)#an array of length 4 consisting all zeros
a

array([0., 0., 0., 0.])

In [26]:
a=np.ones(4)
print(a.dtype)
a

float64


array([1., 1., 1., 1.])

In [27]:
a=np.empty(10)
print(a.dtype)
a

float64


array([6.95235713e-310, 1.44064220e-311, 1.44066246e-311, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [34]:
a=np.arange(1,11,2) ##(start,stop,iteration step)
print(a)
a

[1 3 5 7 9]


array([1, 3, 5, 7, 9])

In [37]:
a=np.linspace(1,10,4,dtype=np.float64)#dividing 1 to 10 in 4 zones
a

array([ 1.,  4.,  7., 10.])

In [38]:
a=np.linspace(0,1,4,dtype=np.float64)
a

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [44]:
a=np.random.random(2)
print(a)
a=np.random.random((2,3))
print(a)

[0.15219913 0.03748949]
[[0.78961968 0.70387991 0.13391724]
 [0.25805584 0.97626536 0.99286385]]


In [50]:
a=np.random.random(10)
a.sort() #sorts the original array
a


array([0.00110766, 0.16271823, 0.22647075, 0.33498383, 0.40647413,
       0.68121769, 0.7648874 , 0.90662388, 0.90993938, 0.98020187])

In [49]:
a=np.random.random(10)
print(np.sort(a))#don't change the actual array 
print(a)

[0.12380363 0.23161413 0.26702879 0.28246471 0.2879012  0.39653713
 0.59914016 0.89564446 0.913192   0.96070568]
[0.913192   0.28246471 0.39653713 0.59914016 0.23161413 0.2879012
 0.96070568 0.12380363 0.89564446 0.26702879]


In [52]:
a=[1,4,2,6,3,1]
b=[5,3,3,3,5,2]
c=a+b
c

[1, 4, 2, 6, 3, 1, 5, 3, 3, 3, 5, 2]

In [58]:
a=np.array([1,4,2,6,3,1])
b=np.array([5,3,2,3,5,2])
c=np.concatenate((a,b))
c


array([1, 4, 2, 6, 3, 1, 5, 3, 2, 3, 5, 2])

In [63]:
a=np.array([1,4,2,6,3,1])
c=a.reshape(3,2)
print(c,c.T)

[[1 4]
 [2 6]
 [3 1]] [[1 2 3]
 [4 6 1]]


In [82]:
a=np.array([1,4,2,6,3,1])
b=np.array([5,3,2,3,5,2])
#return a array with true/false
#true when item is greater than 3
#false otherwise
boolean_arr=a>3
print(boolean_arr)
print(b<3)
print(a[boolean_arr])
a[[True,False,True,False,True,False]]
print(a[a>1])
print(a[a==1])
x=a[(a>5)|(a<3)]

#in python which is slower than numpy
y=[]
for i in a:
    if(i>5 or i<3):
        y.append(int(i))
print(x,y)
    


[False  True False  True False False]
[False False  True False False  True]
[4 6]
[4 2 6 3]
[1 1]
[1 2 6 1] [1, 2, 6, 1]


In [84]:
#Stacking
a1=np.array([[1,2],[2,2]])
a2=np.array([[3,3],[4,4]])

a3=np.vstack((a1,a2))
print(a3)
a4=np.hstack((a1,a2))
print(a4)


[[1 2]
 [2 2]
 [3 3]
 [4 4]]
[[1 2 3 3]
 [2 2 4 4]]


In [99]:
a=np.array([1,4,2,6,3,1])
b=np.array([5,3,2,3,5,2])
a1=np.hsplit(a,3)
print(a1)
a+b #dimension same 
a+2 #called broadcasting
print(a.max())
a/a.max()
c=np.vstack((a,b))
print(c.max())
print(c.max(axis=0))
print(c.max(axis=1))

[array([1, 4]), array([2, 6]), array([3, 1])]
6
6
[5 4 2 6 5 2]
[6 5]


In [104]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.shape)
b=np.array([[1,2]])
print(b.shape)
print(a+b)


[[1 2]
 [3 4]
 [5 6]]
(3, 2)
(1, 2)
[[2 4]
 [4 6]
 [6 8]]


In [108]:
a=np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,19,20])
unique_values,occurance_count=np.unique(a,return_counts=True)
print(unique_values)
print(occurance_count)

[11 12 13 14 15 16 17 18 19 20]
[3 2 2 2 1 1 1 1 1 1]


In [114]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
print(a.shape)
print(b.shape)
# a.dot(b)
print(np.matmul(a,b))

(3, 3)
(3, 3)
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [116]:
a=np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]])
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [125]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
print(z)
z[1,1]=9
print(z)
output[1:4,1:4]=z;
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
