In [2]:
import numpy as np

In [4]:
a=np.array([1.0,2.0,3.0])
a=a*1.6
print(a)

[1.6 3.2 4.8]


In [8]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[1,1]])
c=np.ones(2)
print(a+c)
print(b)
print(a+b)

[[2. 3.]
 [4. 5.]
 [6. 7.]]
[[1 1]]
[[2 3]
 [4 5]
 [6 7]]
